### PR TITLE
Implemented Dice.ValidateTwoPairs() aswell UnitTests for this function

### PR DESCRIPTION
**Pull request by Bananamafia**
Hey, 

I implemented the function and with my UnitTests it worked well, hope it helps and if you have any questions or suggestions, I'd happy to hear from you cause it's my first Contribution :)

The function iterates through all _eyevalues.
First it checks if there are 4 or more times the same _eyevalue. If so, the score prints out 4 * _eyevalue.
Else it checks if there are 2 or more times the same _eyevalue. If so it adds 2*_eyevalue to a temporary score and set the number of pairs to +1. 
When there are 2 or more pairs it sets the score to the temporary score.

### CODE REVIEW

**Comment by Bananamafia** [comment]
It seems I was a few seconds two slow :D

**Comment by maitovelkkis** [comment]
Thanks anyway, and sorry for the inconvenience. Couldn't think of a nice way to implement it yesterday so thought I'd let someone else try. But then when I woke up today, I already had an idea for all of the hand validators and just did them... I would have used your if I hadn't done mine already, I'm just too proud of my version to discard it now :D I'll merge the unit tests anyway, don't mind having more of them.

**Comment by maitovelkkis** [comment]
@Bananamafia Did I somehow merge straight into your branch? I'm still trying to learn github...

**Comment by Bananamafia** [comment]
> Thanks anyway, and sorry for the inconvenience. Couldn't think of a nice way to implement it yesterday so thought I'd let someone else try. But then when I woke up today, I already had an idea for all of the hand validators and just did them... I would have used your if I hadn't done mine already, I'm just too proud of my version to discard it now :D I'll merge the unit tests anyway, don't mind having more of them.

No problem, I totally unserstand this and it's nice to hear you found a solution which suits your style :)

**Comment by Bananamafia** [comment]
> @Bananamafia Did I somehow merge straight into your branch? I'm still trying to learn github...

Haha, till now I only worked on my private Projects, but yes it seems you made changes in my branch, which isn't a big deal, due to the fact I had to update it anyways if I tried to do more commits :D

**Comment by maitovelkkis** [comment]
> No problem, I totally unserstand this and it's nice to hear you found a solution which suits your style :)

Actually, there was a problem in my way which slipped past my own unit tests. Fortunately found a way to fix it with one line, but before I found, I was already thinking maybe I should have used your way after all :D

**Comment by maitovelkkis** [comment]
> Haha, till now I only worked on my private Projects, but yes it seems you made changes in my branch, which isn't a big deal, due to the fact I had to update it anyways if I tried to do more commits :D

I've only worked on other peoples project before, so I don't really know how this side of things works... That's one reason I started this project on github, learning to use it.

**Comment by Bananamafia** [comment]
> > No problem, I totally unserstand this and it's nice to hear you found a solution which suits your style :)
> 
> Actually, there was a problem in my way which slipped past my own unit tests. Fortunately found a way to fix it with one line, but before I found, I was already thinking maybe I should have used your way after all :D

Sounds good ;) I am still trying to figure out a way to update my local repo with your changes 🤔

**Comment by maitovelkkis** [comment]
> Sounds good ;) I am still trying to figure out a way to update my local repo with your changes 🤔

I'm not sure if it's the correct way, but you can make a pull request from my master to your master or experimental branch here. And then merge the pull request.
https://github.com/Bananamafia/long-yatzi/compare/master...maitovelkkis:master

**Comment by Bananamafia** [comment]
> > Sounds good ;) I am still trying to figure out a way to update my local repo with your changes 🤔
> 
> I'm not sure if it's the correct way, but you can make a pull request from my master to your master or experimental branch here. And then merge the pull request.
> [Bananamafia/long-yatzi@master...maitovelkkis:master](https://github.com/Bananamafia/long-yatzi/compare/master...maitovelkkis:master)

Yes I think this works, but I am not quite sure if this is the "offical" way doing this. 
I think there is a built in way to keep in sync, but till now I haven't found a way doing this in the git Add-in for VS

**Comment by Bananamafia** [comment]
@maitovelkkis 

Ah I think I got it. 
I have to make an "Remote Repo" and use Fetch of your Repo and Push to mine.. This seems to be a proper solution.

Btw. it seems to be an issue when thowing a full house it doesn't count as two Pairs.

**Comment by maitovelkkis** [comment]
> > > Sounds good ;) I am still trying to figure out a way to update my local repo with your changes 🤔
> > 
> > 
> > I'm not sure if it's the correct way, but you can make a pull request from my master to your master or experimental branch here. And then merge the pull request.
> > [Bananamafia/long-yatzi@master...maitovelkkis:master](https://github.com/Bananamafia/long-yatzi/compare/master...maitovelkkis:master)
> 
> Yes I think this works, but I am not quite sure if this is the "offical" way doing this.
> I think there is a built in way to keep in sync, but till now I haven't found a way doing this in the git Add-in for VS

I don't know how to use VS with git, but seems that using fetch at your local repo using tortoisegit or git bash, and giving url of my master (https://github.com/maitovelkkis/long-yatzi.git) and then merging FETCH_HEAD to your local branch merges them very neatly.

**Comment by maitovelkkis** [comment]
> Ah I think I got it.
> I have to make an "Remote Repo" and use Fetch of your Repo and Push to mine.. This seems to be a proper solution.
> 
> Btw. it seems to be an issue when thowing a full house it doesn't count as two Pairs.

@Bananamafia 
Good to hear you found solution. And good thing you noticed the problem in ValidateTwoPairs... I fixed it in latest commit, only had to move one line of code.

**Pull request merged**
